### ISSUE TITLE
HIP: multiple failure with ROCm 7.1

### ISSUE THREAD

**Issue by Rombur** [kokkos/kokkos#8635]
ROCm 7.1 was released last week and it breaks multiple tests:
 - `hip.mdrange_large_deep_copy`: Wrong results. Reducing the size (`s`)  from 45 to 22 in `TestMDRange_g.hpp` fixes the issue
 - `hip.triple_nested_parallelism`: Wrong results
 - `hip.team_scan`: Wrong results. The test passes if run individually
 - `hip.team_scan_ret_val`: Wrong results . The test passes if run individually
 - `hip.workgraph_fib`: Wrong results. The test passes if run individually
 - `hip.memory_requirements`: `error(hipErrorInvalidValue)` when calling `hipMemRangeGetAttribute`. The issue appears when determining the coherency mode of a Kokkos::View. It works fine if we use an array allocated with `hipMalloc`
 - `hip.scatterview`: Wrong results. The test passes if run individually
 - `hip.scatterview_devicetype`: Wrong results. The test passes if run individually
 - In `Kokkos_ContainersPerformanceTest_HIP`, we also have a failure for `TEST_CATEGORY.global_2_local`: `Memory access fault by GPU node-32 (Agent handle: 0x1a238e0) on address 0x7f787b4cc000. Reason: Unknown`
 
cc: @khuck-amd

**Comment by khuck-AMD** [comment]
Just starting to investigate, but on my test system, I ran the test suite and had 2 failures: 
```
The following tests FAILED:
          5 - Kokkos_CoreUnitTest_HIP (Subprocess aborted)
         49 - Kokkos_AlgorithmsUnitTest_StdSet_Team_M (SEGFAULT)
```
I re-ran the `Kokkos_AlgorithmsUnitTest_StdSet_Team_M` test by itself with `ctest`, and it failed. I ran it in the debugger, and it succeeded. I ran it from the command line with `./build/algorithms/unit_tests/Kokkos_AlgorithmsUnitTest_StdSet_Team_M` and it succeeded. Something in the ctest environment is squirrely with that one.

Still investigating the others.

**Comment by khuck-AMD** [comment]
For posterity, I ran the docker container with:
```
docker pull rocm/dev-ubuntu-24.04:7.1-complete
docker run -it \
      --network=host \
      --device=/dev/kfd \
      --device=/dev/dri \
      --ipc=host \
      --group-add video \
      -v $(pwd):/jax_dir \
      --name rocm_jax \
rocm/dev-ubuntu-24.04:7.1-complete /bin/bash
```
then in the container, ran:
```
apt update
apt install git cmake vim
git clone https://github.com/kokkos/kokkos.git
cd kokkos

export ROCM_PATH=/opt/rocm-7.1.0
export HSA_XNACK=1

cmake --B build -S . --fresh \
  -D CMAKE_CXX_COMPILER=amdclang++ \
  -D CMAKE_CXX_STANDARD=20 \
  -D CMAKE_PREFIX_PATH=/opt/rocm \
  -D Kokkos_ENABLE_HIP=ON \
  -D Kokkos_ENABLE_TESTS=ON \
  -D GPU_BUILD_TARGETS=gfx90a \
  -D GPU_TARGETS=gfx90a \

cmake --build build --parallel 32
ctest --test-dir build --timeout 30
ctest --test-dir build --timeout 3000 --rerun-failed --output-on-failure
```
The `GPU_BUILD_TARGETS` and `GPU_TARGETS` were necessary because otherwise CMake would set them to `gfx90a:sramecc+:xnack+` which conflicts with the flag that Kokkos sets for `--offload-arch=gfx90a`. `export ROCM_PATH=/opt/rocm-7.1.0` was necessary because the CMake macro in `cmake/Modules/FindTPLROCM.cmake` only checks the environment variable, not the CMake variable.

**Comment by khuck-AMD** [comment]
...also, I didn't get the "wrong results" results. I am running on an MI250X system.

**Comment by Rombur** [comment]
I have updated the issue to reflect that several failing tests are passing when I run them individually

**Comment by Rombur** [comment]
All the tests are passing if I disable `hipMallocAsync`

**Comment by JBludau** [comment]
I am seeing this on MI300A with Rocm 7.1 using hipcc

```
26%] Building CXX object core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_HIP.dir/hip/TestHIP_ViewMove.cpp.o
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/rocm-7.1.0/lib/llvm/bin/clang-20 -cc1 -triple amdgcn-amd-amdhsa -aux-triple x86_64-unknown-linux-gnu -Werror=atomic-alignment -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name TestHIP_ViewMove.cpp -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=none -fno-rounding-math -mconstructor-aliases -aux-target-cpu x86-64 -fcuda-is-device -fno-threadsafe-statics -mllvm -amdgpu-internalize-symbols -fcuda-allow-variadic-functions -fvisibility=hidden -fapply-global-visibility-to-externs -mlink-builtin-bitcode /opt/rocm-7.1.0/lib/llvm/lib/clang/20/lib/amdgcn/bitcode/hip.bc -mlink-builtin-bitcode /opt/rocm-7.1.0/lib/llvm/lib/clang/20/lib/amdgcn/bitcode/ocml.bc -mlink-builtin-bitcode /opt/rocm-7.1.0/lib/llvm/lib/clang/20/lib/amdgcn/bitcode/ockl.bc -mlink-builtin-bitcode /opt/rocm-7.1.0/lib/llvm/lib/clang/20/lib/amdgcn/bitcode/oclc_daz_opt_off.bc -mlink-builtin-bitcode /opt/rocm-7.1.0/lib/llvm/lib/clang/20/lib/amdgcn/bitcode/oclc_unsafe_math_off.bc -mlink-builtin-bitcode /opt/rocm-7.1.0/lib/llvm/lib/clang/20/lib/amdgcn/bitcode/oclc_finite_only_off.bc -mlink-builtin-bitcode /opt/rocm-7.1.0/lib/llvm/lib/clang/20/lib/amdgcn/bitcode/oclc_correctly_rounded_sqrt_on.bc -mlink-builtin-bitcode /opt/rocm-7.1.0/lib/llvm/lib/clang/20/lib/amdgcn/bitcode/oclc_wavefrontsize64_on.bc -mlink-builtin-bitcode /opt/rocm-7.1.0/lib/llvm/lib/clang/20/lib/amdgcn/bitcode/oclc_isa_version_942.bc -mlink-builtin-bitcode /opt/rocm-7.1.0/lib/llvm/lib/clang/20/lib/amdgcn/bitcode/oclc_abi_version_600.bc -target-cpu gfx942 -debug-info-kind=constructor -dwarf-version=5 -debugger-tuning=gdb -mllvm -amdgpu-spill-cfi-saved-regs -gheterogeneous-dwarf=diexpression -fdebug-compilation-dir=/kokkos/build/core/unit_test -resource-dir /opt/rocm-7.1.0/lib/llvm/lib/clang/20 -MT core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_HIP.dir/hip/TestHIP_ViewMove.cpp.o -sys-header-deps -internal-isystem /opt/rocm-7.1.0/lib/llvm/lib/clang/20/include/cuda_wrappers -idirafter /opt/rocm-7.1.0/lib/llvm/bin/../../../include -include __clang_hip_runtime_wrapper.h -isystem /kokkos/tpls/gtest -isystem /kokkos/tpls/desul/include -isystem /kokkos/tpls/mdspan/include -D KOKKOS_DEPENDENCE -D USE_PROF_API=1 -D __HIP_PLATFORM_AMD__=1 -I /kokkos/build/core/unit_test -I /kokkos/core/unit_test -I /kokkos/core/unit_test/category_files -I /kokkos/build -I /kokkos/build/core/src -I /kokkos/core/src -I /kokkos/build/containers/src -I /kokkos/containers/src -I /kokkos/build/algorithms/src -I /kokkos/algorithms/src -I /kokkos/build/simd/src -I /kokkos/simd/src -D NDEBUG -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/x86_64-linux-gnu/c++/13 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/backward -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/x86_64-linux-gnu/c++/13 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/backward -internal-isystem /opt/rocm-7.1.0/lib/llvm/lib/clang/20/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/13/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /opt/rocm-7.1.0/lib/llvm/lib/clang/20/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/13/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O2 -std=gnu++20 -fdeprecated-macro -fno-autolink -ferror-limit 19 -fhip-new-launch-api -fno-rtti -fgnuc-version=4.2.1 -fno-implicit-modules -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -cuid=25911987101edb25 -fcuda-allow-variadic-functions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/TestHIP_ViewMove-gfx942-0c20b5.o -x hip /kokkos/build/core/unit_test/hip/TestHIP_ViewMove.cpp
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'CallGraph Pass Manager' on module '/kokkos/build/core/unit_test/hip/TestHIP_ViewMove.cpp'.
4.	Running pass 'Rename Disconnected Subregister Components' on function '@_ZN12_GLOBAL__N_127check_moved_from_view_stateIN6Kokkos4ViewIPPdJNS1_3HIPEEEEEEiT_'
 #0 0x00005648b6eb88c2 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/rocm-7.1.0/lib/llvm/bin/clang-20+0x29678c2)
 #1 0x00005648b6eb5d66 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f77fdb67330 (/lib/x86_64-linux-gnu/libc.so.6+0x45330)
 #3 0x00005648b63916fb (anonymous namespace)::RenameIndependentSubregs::renameComponents(llvm::LiveInterval&) const RenameIndependentSubregs.cpp:0:0
 #4 0x00005648b639301a (anonymous namespace)::RenameIndependentSubregs::runOnMachineFunction(llvm::MachineFunction&) RenameIndependentSubregs.cpp:0:0
 #5 0x00005648b622df78 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
 #6 0x00005648b680a579 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/rocm-7.1.0/lib/llvm/bin/clang-20+0x22b9579)
 #7 0x00005648b5e65d11 (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) CallGraphSCCPass.cpp:0:0
 #8 0x00005648b680982b llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/rocm-7.1.0/lib/llvm/bin/clang-20+0x22b882b)
 #9 0x00005648b7144825 clang::emitBackendOutput(clang::CompilerInstance&, clang::CodeGenOptions&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (/opt/rocm-7.1.0/lib/llvm/bin/clang-20+0x2bf3825)
#10 0x00005648b77ba34c clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/rocm-7.1.0/lib/llvm/bin/clang-20+0x326934c)
#11 0x00005648b924494c clang::ParseAST(clang::Sema&, bool, bool) (/opt/rocm-7.1.0/lib/llvm/bin/clang-20+0x4cf394c)
#12 0x00005648b7ac883e clang::FrontendAction::Execute() (/opt/rocm-7.1.0/lib/llvm/bin/clang-20+0x357783e)
#13 0x00005648b7a4ab0b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/rocm-7.1.0/lib/llvm/bin/clang-20+0x34f9b0b)
#14 0x00005648b7b9e8ab clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/rocm-7.1.0/lib/llvm/bin/clang-20+0x364d8ab)
#15 0x00005648b53ccb59 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/rocm-7.1.0/lib/llvm/bin/clang-20+0xe7bb59)
#16 0x00005648b53c4daa ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#17 0x00005648b53c8455 clang_main(int, char**, llvm::ToolContext const&) (/opt/rocm-7.1.0/lib/llvm/bin/clang-20+0xe77455)
#18 0x00005648b52c967a main (/opt/rocm-7.1.0/lib/llvm/bin/clang-20+0xd7867a)
#19 0x00007f77fdb4c1ca (/lib/x86_64-linux-gnu/libc.so.6+0x2a1ca)
#20 0x00007f77fdb4c28b __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28b)
#21 0x00005648b53c4805 _start (/opt/rocm-7.1.0/lib/llvm/bin/clang-20+0xe73805)
clang++: error: unable to execute command: Segmentation fault (core dumped)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
```

**Comment by jjellio** [comment]
7.1 landed on the LLNL machines, I'll run my testing stuff and see how it goes (I can do Mi250x and Mi300A).

we did have the issue with 7.0 RCs where hip malloc async was the culprit, and disabling it resolved the issues, then RC4 fixed whatever it was. (with RC4 and 7.0.x my testing was clean).

**Comment by JBludau** [comment]
> 7.1 landed on the LLNL machines, I'll run my testing stuff and see how it goes (I can do Mi250x and Mi300A).
> 
> we did have the issue with 7.0 RCs where hip malloc async was the culprit, and disabling it resolved the issues, then RC4 fixed whatever it was. (with RC4 and 7.0.x my testing was clean).

thanks for checking! yeah, on pre mi300 we saw the malloc async being the problem but mi300a even refused to compile our unit tests

**Comment by jjellio** [comment]
I've got quite a bit of data.  I usually focus on RDC=ON, but let's just focus on static build (I don't test shared).

For a static build on Mi250X

<details>
<summary>Ctest</summary>

```
94% tests passed, 3 tests failed out of 51

Label Time Summary:
Kokkos    = 718.52 sec*proc (50 tests)

Total Test time (real) = 199.34 sec

The following tests FAILED:
          5 - Kokkos_CoreUnitTest_HIP (Failed)
         32 - Kokkos_UnitTest_Random (SEGFAULT)
         42 - Kokkos_AlgorithmsUnitTest_StdSet_Team_E (SEGFAULT)
Errors while running CTest
```
</details>

For the HIP core test, I then run each gtest on its own.
<details>
<summary>There is 1 failing test inside the HIP Core:</summary>

```
[jjellio@rzadams1017 05:57 kokkos-linker-logs-7.1.0]$ less rocm-7.1.0_rocm-7.1.0_rdc-OFF_thinOffload-OFF_thin-OFF_newDriver-OFF_splitting-OFF_partitions-1_maxdepth-FALSE_GFX90A/Kokkos_CoreUnitTest_HIP.txt  | grep PASSED | wc -l
462
[jjellio@rzadams1017 05:58 kokkos-linker-logs-7.1.0]$ less rocm-7.1.0_rocm-7.1.0_rdc-OFF_thinOffload-OFF_thin-OFF_newDriver-OFF_splitting-OFF_partitions-1_maxdepth-FALSE_GFX90A/Kokkos_CoreUnitTest_HIP.txt  | grep FAILED | wc -l
1
```
</details>

<details>
<summary>The rocgdb backtrace from all threads:</summary>

```
hip.memory_requirements

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x1555471ff700 (LWP 2817621)]
[New Thread 0x155546ffe700 (LWP 2817622)]
[Thread 0x155546ffe700 (LWP 2817622) exited]
[New Thread 0x1555469ff700 (LWP 2817623)]
Note: Google Test filter = hip.memory_requirements
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from hip
[ RUN      ] hip.memory_requirements
unknown file: Failure
C++ exception with description "hipMemRangeGetAttribute( &memInfo, sizeof(hipMemRangeCoherencyMode), hipMemRangeAttributeCoherencyMode, container.data(), allocationSize) error( hipErrorInvalidValue): invalid argument /usr/workspace/jjellio/elcap/rocm-linker-tests/kokkos/core/unit_test/hip/TestHIP_Memory_Requirements.cpp:30" thrown in the test body.
[  FAILED  ] hip.memory_requirements (7 ms)
[----------] 1 test from hip (7 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (7 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] hip.memory_requirements

 1 FAILED TEST
[Thread 0x1555469ff700 (LWP 2817623) exited]
[Thread 0x1555471ff700 (LWP 2817621) exited]
[Inferior 1 (process 2817612) exited with code 01]

```
</details>

<details>
<summary>My SHA:</summary>

```
commit 0fcbdcef291f76b2c65704a1e81dc92a97596aac (HEAD -> develop, origin/develop, origin/HEAD)
Merge: aa0b791de 2bebf2db8
Author: Damien L-G <dalg24@gmail.com>
Date:   Tue Aug 19 18:18:29 2025 -0400

    Merge pull request #8334 from dalg24/cleanup_reduction_identity_complex
    
    Cleanup `reduction_identity<complex<T>>` specialization
```
</details>

(I DO set: export HSA_XNACK=1 even on Mi250X)


<details>
<summary>My Cmake</summary>

```
cmake \
 "-GNinja" \
 "-DKokkos_ENABLE_TESTS=ON" \
 "-DKokkos_ENABLE_ROCTHRUST:BOOL=OFF" \
 "-DPYTHON_EXECUTABLE=/usr/tce/bin/python3" \
 "-DCMAKE_BUILD_TYPE:STRING=Release" \
 "-DBUILD_SHARED_LIBS:BOOL=OFF" \
 "-DKokkos_ENABLE_SERIAL:BOOL=ON" \
 "-DKokkos_ENABLE_HIP:BOOL=ON" \
 "-DCMAKE_AR=/opt/rocm-7.1.0/llvm/bin/llvm-ar" \
 "-DCMAKE_RANLIB=/opt/rocm-7.1.0/llvm/bin/llvm-ranlib" \
 "-DKokkos_ARCH_AMD_GFX90A:BOOL=ON" \
 "-DKokkos_ARCH_NATIVE=ON" \
 "-DKokkos_ENABLE_HIP_RELOCATABLE_DEVICE_CODE:BOOL=OFF" \
 "-DCMAKE_EXE_LINKER_FLAGS=-x none --hip-link -mllvm -amdgpu-early-inline-all=false -mllvm -amdgpu-function-calls=false   -Wl,-rpath,/opt/rocm-7.1.0/lib/:/opt/rocm-7.1.0/llvm/lib/ " \
 "-DCMAKE_SHARED_LINKER_FLAGS=-x none --hip-link -mllvm -amdgpu-early-inline-all=false -mllvm -amdgpu-function-calls=false   " \
 "-DCMAKE_CXX_COMPILER=/opt/rocm-7.1.0/bin/amdclang++" \
 "-DCMAKE_CXX_FLAGS=--rocm-path=/opt/rocm-7.1.0 -x hip -mllvm -amdgpu-early-inline-all=false -mllvm -amdgpu-function-calls=false  -g  " \
 "-DCMAKE_CXX_STANDARD=20" \
/usr/workspace/jjellio/elcap/rocm-linker-tests/kokkos 2>&1 | tee configure_kokkos_performance.log 
```
</details>


This seems to be what Kevin Huck (AMD) reported?


Mi300A looks like a mess - but I'm betting turning off Async malloc will clean it up some.  It's not clear to me if the AMD compiler flags (early-inline-all and gpu-function-calls are even meaningful now - I thought they were deprecated. - I never deleted them, as we set these because they caused issues with build times)

I scanned the remaining Mi250X builds - RDC ON, AMD's module splitting - and the `hip.memory_requirements` appears to be the only failures between static only vs RDC .

**Comment by jjellio** [comment]
Static build of Mi300A: (Not disabling Async malloc)

<details>
<summary>Ctest Output</summary>

```
35% tests passed, 33 tests failed out of 51

Label Time Summary:
Kokkos    = 134.03 sec*proc (50 tests)

Total Test time (real) =  37.67 sec

The following tests FAILED:
          2 - Kokkos_CoreUnitTest_HIP_ViewSupport (SEGFAULT)
          3 - Kokkos_CoreUnitTest_Serial1 (SEGFAULT)
          4 - Kokkos_CoreUnitTest_Serial2 (SEGFAULT)
          5 - Kokkos_CoreUnitTest_HIP (SEGFAULT)
          6 - Kokkos_CoreUnitTest_HIPGraphAtomicLocks (SEGFAULT)
          9 - Kokkos_CoreUnitTest_HIPInterOpGraph (SEGFAULT)
         10 - Kokkos_CoreUnitTest_Default (SEGFAULT)
         11 - Kokkos_CoreUnitTest_InitializeFinalize (Failed)
         13 - Kokkos_CoreUnitTest_KokkosP (SEGFAULT)
         21 - Kokkos_IncrementalTest_HIP (SEGFAULT)
         28 - Kokkos_ContainersUnitTest_Serial (SEGFAULT)
         29 - Kokkos_ContainersUnitTest_HIP (SEGFAULT)
         30 - Kokkos_ContainersPerformanceTest_HIP (SEGFAULT)
         31 - Kokkos_UnitTest_Sort (SEGFAULT)
         32 - Kokkos_UnitTest_Random (SEGFAULT)
         33 - Kokkos_AlgorithmsUnitTest_StdSet_A (SEGFAULT)
         34 - Kokkos_AlgorithmsUnitTest_StdSet_B (SEGFAULT)
         35 - Kokkos_AlgorithmsUnitTest_StdSet_C (SEGFAULT)
         36 - Kokkos_AlgorithmsUnitTest_StdSet_D (SEGFAULT)
         37 - Kokkos_AlgorithmsUnitTest_StdSet_E (SEGFAULT)
         38 - Kokkos_AlgorithmsUnitTest_StdSet_Team_A (SEGFAULT)
         39 - Kokkos_AlgorithmsUnitTest_StdSet_Team_B (SEGFAULT)
         40 - Kokkos_AlgorithmsUnitTest_StdSet_Team_C (SEGFAULT)
         41 - Kokkos_AlgorithmsUnitTest_StdSet_Team_D (SEGFAULT)
         42 - Kokkos_AlgorithmsUnitTest_StdSet_Team_E (SEGFAULT)
         43 - Kokkos_AlgorithmsUnitTest_StdSet_Team_F (SEGFAULT)
         44 - Kokkos_AlgorithmsUnitTest_StdSet_Team_G (SEGFAULT)
         45 - Kokkos_AlgorithmsUnitTest_StdSet_Team_H (SEGFAULT)
         46 - Kokkos_AlgorithmsUnitTest_StdSet_Team_I (SEGFAULT)
         47 - Kokkos_AlgorithmsUnitTest_StdSet_Team_L (SEGFAULT)
         48 - Kokkos_AlgorithmsUnitTest_StdSet_Team_M (SEGFAULT)
         49 - Kokkos_AlgorithmsUnitTest_StdSet_Team_P (SEGFAULT)
         50 - Kokkos_AlgorithmsUnitTest_StdSet_Team_Q (SEGFAULT)
Errors while running CTest
```
</details>

<details>
<summary>Cmake</summary>

```
cmake \
 "-GNinja" \
 "-DKokkos_ENABLE_TESTS=ON" \
 "-DKokkos_ENABLE_ROCTHRUST:BOOL=OFF" \
 "-DPYTHON_EXECUTABLE=/usr/tce/bin/python3" \
 "-DCMAKE_BUILD_TYPE:STRING=Release" \
 "-DBUILD_SHARED_LIBS:BOOL=OFF" \
 "-DKokkos_ENABLE_SERIAL:BOOL=ON" \
 "-DKokkos_ENABLE_HIP:BOOL=ON" \
 "-DCMAKE_AR=/opt/rocm-7.1.0/llvm/bin/llvm-ar" \
 "-DCMAKE_RANLIB=/opt/rocm-7.1.0/llvm/bin/llvm-ranlib" \
 "-DKokkos_ARCH_AMD_GFX942_APU:BOOL=ON" \
 "-DKokkos_ARCH_NATIVE=ON" \
 "-DKokkos_ENABLE_HIP_RELOCATABLE_DEVICE_CODE:BOOL=OFF" \
 "-DCMAKE_EXE_LINKER_FLAGS=-x none --hip-link -mllvm -amdgpu-early-inline-all=false -mllvm -amdgpu-function-calls=false   -Wl,-rpath,/opt/rocm-7.1.0/lib/:/opt/rocm-7.1.0/llvm/lib/ " \
 "-DCMAKE_SHARED_LINKER_FLAGS=-x none --hip-link -mllvm -amdgpu-early-inline-all=false -mllvm -amdgpu-function-calls=false   " \
 "-DCMAKE_CXX_COMPILER=/opt/rocm-7.1.0/bin/amdclang++" \
 "-DCMAKE_CXX_FLAGS=--rocm-path=/opt/rocm-7.1.0 -x hip -mllvm -amdgpu-early-inline-all=false -mllvm -amdgpu-function-calls=false  -g  " \
 "-DCMAKE_CXX_STANDARD=20" \
/usr/workspace/jjellio/elcap/rocm-linker-tests/kokkos 2>&1 | tee configure_kokkos_performance.log 
```
</details>


Lots of failures >100 in Hip Core... it's going to take awhile for it to run through them all and get backtraces

Edit:
Indeed.... disable Hip Malloc Async.... 100% clean on MI300A.

```
100% tests passed, 0 tests failed out of 51

Label Time Summary:
Kokkos    = 598.02 sec*proc (50 tests)
``` 

The delta in the Cmake options for these two Mi300A builds is:
`"-DKokkos_ENABLE_IMPL_HIP_MALLOC_ASYNC=OFF" `

(I haven't gotten data from RDC)

**Comment by jjellio** [comment]
AMD sent back that they have identified the MI300A issue internally and will let us know when a fix is going live.

I think the summary of issues:
1. MI250X - the memory traits query API changed (?) - that makes that test syntactically wrong
2. MI300A - async malloc usage is broken (a bug on AMD's end), and the work around is disabling that for 300A. 

I still haven't had time to push Trilinos through on 7.1 (a bug in Trilinos currently blocks me from testing it due to Device MPI usage).

**Comment by JBludau** [comment]
I am still running into a compiler ICE for `TestHIP_ViewMove.cpp` with:
```
HIP version: 7.1.52802-26aae437f6
AMD clang version 20.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-7.1.1 25444 27682a16360e33e37c4f3cc6adf9a620733f8fe1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```
My configure options:
```
cmake -B build -DKokkos_ENABLE_HIP=ON -DKokkos_ARCH_AMD_GFX942_APU=ON -DKokkos_ARCH_NATIVE=ON -DCMAKE_CXX_COMPILER=hipcc -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_SERIAL=ON
```
A user reported not seeing this with:
```
HIP version: 7.1.26081-9999
AMD clang version 20.0.0git
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

@khuck-AMD is that known? `ROCm 7.2` did not have the problem

**Comment by khuck-AMD** [comment]
This is cross referenced here: https://github.com/kokkos/kokkos/issues/8884, the issue is with upstream clang and is being addressed. Maybe disabling this test for versions >= 7.1 is a good idea for now, I don't know when the fix will be released in amdclang. That said, it should be dependent on the clang version, not the rocm version.

**Comment by JBludau** [comment]
> This is cross referenced here: [#8884](https://github.com/kokkos/kokkos/issues/8884), the issue is with upstream clang and is being addressed. Maybe disabling this test for versions >= 7.1 is a good idea for now, I don't know when the fix will be released in amdclang. That said, it should be dependent on the clang version, not the rocm version.

So it is also in clang 20? The main difference to #8884 is that this is failing in a different test and only in the device compilation. Can you confirm that it is the same underlying issue in upstream Clang?
The test that is ICEing here is one we really care about.

**Comment by khuck-AMD** [comment]
I have done some testing with newer ROCm releases, and 7.12.0 development branch works fine, as does rocm/7.2.0. Those both use clang 22. Testing with 7.1.0 (clang 20) results in the ICE you reported above.
